[garden]
title = "wiki"
root = "i.root"
attrs = "caml"

[doc]
[doc.kind]
[doc.kind.doc]
path = "/content/entries/"
color = "#3e5c50"
[doc.kind.zombie]
emoji = "🧟"
color = "#959DA5"
[doc.kind.template]
path = "templates/"
prefix = "t."
emoji = "🧩"
color = "#F8F0E3"
[lint]
indent_kind = "space"
indent_size = 2
mkdn_bullet = true
wikilink = true
